<?php 




/**
* Implements hook_menu()
 */  

function my_form_menu(){
 $items = array();
   $items['examples/form'] = array(
    'title' => t('Form Example'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('frist_form'),
    'access callback' => TRUE
  );
    return $items;
}
  


/**
*   Define form
*/
function frist_form($form_state){

 $form['first_name']=array(
     '#title' => t('First name'),
     '#type' => 'textfield',
     '#default_value' =>  t('Frist name'),
     
  );

 $form['last_name']=array(
     '#title' => t('Last name'),
     '#type' => 'textfield',
     '#default_value' =>  t('Last name'),
     
  );

$age = range(1, 90);
  $form['age'] = array(
       '#type' => 'select',
       '#title' => t('Age'),
       '#options' => drupal_map_assoc($age),
   );
    
 $form['film_category']=array(
      '#type' => 'radios',
      '#options' => array(
      'fantasy' => t('Fantasy'),
      'action' => t('Action'),
      'crime' => t('Crime') ,
           ),
        '#title' => t('Category'),
     );
 
  $form['fantasy']=array(
  '#title' => t('Filmele care fac parte din Fantasy'),
  '#options' => $info=db_form(8),
  '#type'=>'checkboxes',
  '#states' => array(
      'visible' => array(
      ':input[name="film_category"]' => array('value' => 'fantasy'),

      ),

    ),
  );
  
  $form['action']=array(
  '#type'=>'checkboxes',
  '#title' => t('Filmele care fac parte din Action'),
  '#options' => $info=db_form(3),
  '#states' => array(
      'visible' => array(
      ':input[name="film_category"]' => array('value' => 'action'),

        ),
       ),
     );
  $form['crime']=array(
  '#title' => t('Filmele care fac parte din Crime'),
  '#type'=>'checkboxes',
  '#options' => $info=db_form(3),
  '#states' => array(
      'visible' => array(
      ':input[name="film_category"]' => array('value' => 'crime'),

        ),
       ),
       );



   $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
     );

  return $form;
 }
        
/**
*Validation submit
*/


// function frist_form_submit($form, &$form_state){

//  //variable_set('site_name', $form_state['values']['sname']);
  
   
// }

// /**
// *Validation fields
// */

// // function frist_form_validate($form, &$form_state){
// //   dpm($form_state);
// //    if(!preg_match("/^[a-zA-Z0-9]+$/",$form_state['values']['sname']))
// //     form_set_error("sname",$form_state['values']['sname']."is not name");

// //  }

function db_form($id){
$query = new EntityFieldQuery();
$query->entityCondition('entity_type', 'node');
$query ->fieldCondition('field_categories', 'tid',$id);
$query -> entityCondition('bundle', 'movie');	
     $result = $query -> execute();
  if (isset($result['node'])){
    $news_items_nids = array_keys($result['node']);
    $news_items = entity_load('node',$news_items_nids);
    
 }
 //dpm($news_items);
//$node_view = array();

foreach ($news_items as $node ){
	
 	$node_view [$node->nid] = $node->title; 
 	
      } 
   //  dpm($node_view);

return $node_view;
  }


function frist_form_submit($form, &$form_state) {

	$id_film = $form_state ['values']['fantasy'];
	dpm($id_film);
  $query = db_insert('form_table')
    ->fields(array(
      'nume' => $form_state['values']['first_name'],
      'prenume' => $form_state['values']['last_name'],
      'virsta'   => $form_state['values']['age'],
      //'id_film' =>  $form_state['values']['fantasy'],
      // 'id_film' =>  $form_state['values']['action'],
      // 'id_film' =>  $form_state['values']['crime'],
          ) )
    ->execute();
  if ($query > 0) {
    drupal_set_message(t('Data has been successfully sent.'));
  }
  else {
    drupal_set_message(t("Data hasn't been sent."), 'error');
  }
  //dpm($form_state);
}